-- MySQL Script generated by MySQL Workbench
-- 06/21/15 23:05:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `university` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `university` ;

-- -----------------------------------------------------
-- Table `university`.`faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`faculties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `faculties_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_departments_faculties1_idx` (`faculties_id` ASC),
  CONSTRAINT `fk_departments_faculties1`
    FOREIGN KEY (`faculties_id`)
    REFERENCES `university`.`faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`professors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `departments_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_professor_departments1_idx` (`departments_id` ASC),
  CONSTRAINT `fk_professor_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `university`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `departments_id` INT NOT NULL,
  `professors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_courses_departments1_idx` (`departments_id` ASC),
  INDEX `fk_courses_professor1_idx` (`professors_id` ASC),
  CONSTRAINT `fk_courses_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `university`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_professor1`
    FOREIGN KEY (`professors_id`)
    REFERENCES `university`.`professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `faculties_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_students_faculties1_idx` (`faculties_id` ASC),
  CONSTRAINT `fk_students_faculties1`
    FOREIGN KEY (`faculties_id`)
    REFERENCES `university`.`faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`titles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`courses_has_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`courses_has_students` (
  `courses_id` INT NOT NULL,
  `students_id` INT NOT NULL,
  PRIMARY KEY (`courses_id`, `students_id`),
  INDEX `fk_courses_has_students_students1_idx` (`students_id` ASC),
  INDEX `fk_courses_has_students_courses1_idx` (`courses_id` ASC),
  CONSTRAINT `fk_courses_has_students_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `university`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_has_students_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `university`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`professors_has_titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`professors_has_titles` (
  `professors_id` INT NOT NULL,
  `titles_id` INT NOT NULL,
  PRIMARY KEY (`professors_id`, `titles_id`),
  INDEX `fk_professors_has_titles_titles1_idx` (`titles_id` ASC),
  INDEX `fk_professors_has_titles_professors1_idx` (`professors_id` ASC),
  CONSTRAINT `fk_professors_has_titles_professors1`
    FOREIGN KEY (`professors_id`)
    REFERENCES `university`.`professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professors_has_titles_titles1`
    FOREIGN KEY (`titles_id`)
    REFERENCES `university`.`titles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
